# Travis continuous integration for kitodo-production

language: java

cache:

sudo: required

env: DB=mysql

services:
  - mysql

script: mvn clean install -Pall-tests,flyway

before_script:
  - cp config/database.yml.travis config/database.yml
  - mysql -u root -e 'CREATE DATABASE kitodo;'
  - mysql -u root -e "CREATE USER 'kitodo'@'localhost' IDENTIFIED BY 'kitodo';"
  - mysql -u root -e "GRANT ALL ON kitodo.* TO 'kitodo'@'localhost';"
